import argparse
import asyncio
import os
from argparse import Namespace

from openhands.core.logger import openhands_logger as logger
from openhands.resolver.interfaces.issue import Issue
from openhands.resolver.issue_resolver import IssueResolver


class PRReviewer(IssueResolver):
    """Pull Request Reviewer that extends IssueResolver.

    This class provides functionality to review pull requests by running
    the OpenHands agent and posting a summary comment with the results.

    Inherits all initialization and configuration from IssueResolver, and adds
    PR-specific review functionality including summary generation and comment posting.
    """

    def __init__(self, args: Namespace) -> None:
        """Initialize the PRReviewer with the given parameters.

        Args:
            args: Namespace containing all required arguments inherited from IssueResolver,
                  including owner, repo, token, username, issue_number, etc.
        """
        super().__init__(args)
        logger.info(f'Initialized PRReviewer for PR #{self.issue_number}')

    async def review(self) -> None:
        """Execute the PR review process.

        This method orchestrates the full PR review workflow:
        1. Extracts the PR information
        2. Analyzes the PR content and changes
        3. Generates a review summary
        4. Posts a comment with the review
        """
        logger.info(f'Starting PR review for #{self.issue_number}')

        # Extract PR information
        issue = self.extract_issue()

        # Analyze the PR and generate review
        review_summary = await self._analyze_pr(issue)

        # Post the review comment
        self._post_review_comment(review_summary)

        logger.info(f'Completed PR review for #{self.issue_number}')

    async def _analyze_pr(self, issue: Issue) -> str:
        """Analyze the PR and generate a review.

        Args:
            issue: The Issue object containing PR information

        Returns:
            A formatted review summary
        """
        logger.info(f'Analyzing PR #{issue.number}: {issue.title}')

        # Build analysis of the PR
        analysis_parts = []

        # Add basic PR information
        analysis_parts.append(f'## PR Review: {issue.title}\n\n')

        # Analyze PR description
        if issue.body:
            analysis_parts.append('### PR Description\n')
            analysis_parts.append(f'{issue.body[:500]}...\n\n' if len(issue.body) > 500 else f'{issue.body}\n\n')

        # Analyze review comments if present
        if issue.review_comments:
            analysis_parts.append(f'### Review Comments ({len(issue.review_comments)} found)\n')
            for idx, comment in enumerate(issue.review_comments[:5], 1):
                analysis_parts.append(f'{idx}. {comment[:200]}...\n' if len(comment) > 200 else f'{idx}. {comment}\n')
            if len(issue.review_comments) > 5:
                analysis_parts.append(f'\n... and {len(issue.review_comments) - 5} more comments\n')
            analysis_parts.append('\n')

        # Analyze review threads if present
        if issue.review_threads:
            analysis_parts.append(f'### Review Threads ({len(issue.review_threads)} found)\n')
            for idx, thread in enumerate(issue.review_threads[:3], 1):
                analysis_parts.append(f'{idx}. **Files**: {", ".join(thread.files)}\n')
                analysis_parts.append(f'   **Comment**: {thread.comment[:200]}...\n\n' if len(thread.comment) > 200 else f'   **Comment**: {thread.comment}\n\n')
            if len(issue.review_threads) > 3:
                analysis_parts.append(f'... and {len(issue.review_threads) - 3} more threads\n')
            analysis_parts.append('\n')

        # Add branches info
        if issue.head_branch and issue.base_branch:
            analysis_parts.append(f'### Branch Information\n')
            analysis_parts.append(f'- **Base**: `{issue.base_branch}`\n')
            analysis_parts.append(f'- **Head**: `{issue.head_branch}`\n\n')

        # Add closing issues if present
        if issue.closing_issues:
            analysis_parts.append(f'### Related Issues\n')
            analysis_parts.append(f'This PR closes: {", ".join(issue.closing_issues)}\n\n')

        analysis_parts.append('---\n')
        analysis_parts.append('*Review generated by OpenHands PR Reviewer*\n')

        return ''.join(analysis_parts)

    def _post_review_comment(self, summary: str) -> None:
        """Post the review summary as a comment on the PR.

        Args:
            summary: The formatted summary to post
        """
        logger.info(f'Posting review comment for PR #{self.issue_number}')
        self.issue_handler.send_comment_msg(self.issue_number, summary)
        logger.info('Review comment posted successfully')


def main() -> None:
    """Main entry point for the PR reviewer CLI.

    Parses command-line arguments, initializes the PRReviewer, and executes
    the review process.
    """
    parser = argparse.ArgumentParser(
        description='Review a pull request using the OpenHands agent.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Review a PR with basic options
  python -m openhands.resolver.review_pr \\
    --selected-repo owner/repo \\
    --issue-number 123 \\
    --token $GITHUB_TOKEN \\
    --username myuser

  # Review a PR with custom LLM settings
  python -m openhands.resolver.review_pr \\
    --selected-repo owner/repo \\
    --issue-number 123 \\
    --token $GITHUB_TOKEN \\
    --username myuser \\
    --llm-model gpt-4 \\
    --llm-api-key $OPENAI_API_KEY
        """,
    )

    # Required arguments
    parser.add_argument(
        '--selected-repo',
        required=True,
        help='Repository in owner/repo format',
    )
    parser.add_argument(
        '--issue-number',
        type=int,
        required=True,
        help='PR number to review',
    )

    # Authentication arguments
    parser.add_argument(
        '--token',
        type=str,
        help='GitHub token (can also use GITHUB_TOKEN env var)',
    )
    parser.add_argument(
        '--username',
        type=str,
        help='GitHub username (can also use GIT_USERNAME env var)',
    )
    parser.add_argument(
        '--base-domain',
        type=str,
        help='Base domain for git server (e.g., github.com, gitlab.com)',
    )

    # Output and iteration settings
    parser.add_argument(
        '--output-dir',
        type=str,
        default='output',
        help='Output directory for results (default: output)',
    )
    parser.add_argument(
        '--max-iterations',
        type=int,
        default=50,
        help='Maximum number of agent iterations (default: 50)',
    )

    # LLM configuration arguments
    parser.add_argument(
        '--llm-model',
        type=str,
        help='LLM model to use',
    )
    parser.add_argument(
        '--llm-api-key',
        type=str,
        help='API key for the LLM',
    )
    parser.add_argument(
        '--llm-base-url',
        type=str,
        help='Base URL for the LLM API',
    )

    # Container and runtime arguments
    parser.add_argument(
        '--base-container-image',
        type=str,
        help='Base container image to use',
    )
    parser.add_argument(
        '--runtime-container-image',
        type=str,
        help='Runtime container image to use',
    )
    parser.add_argument(
        '--runtime',
        type=str,
        default='docker',
        help='Runtime to use (default: docker)',
    )

    # Additional configuration arguments
    parser.add_argument(
        '--prompt-file',
        type=str,
        help='Path to custom prompt template file',
    )
    parser.add_argument(
        '--repo-instruction-file',
        type=str,
        help='Path to repository-specific instruction file',
    )
    parser.add_argument(
        '--is-experimental',
        action='store_true',
        help='Enable experimental features',
    )
    parser.add_argument(
        '--comment-id',
        type=int,
        help='Specific comment ID to focus on',
    )

    args = parser.parse_args()

    # Set issue type to PR for PR review
    args.issue_type = 'pr'

    logger.info('Initializing PR reviewer...')
    reviewer = PRReviewer(args)

    logger.info('Starting PR review process...')
    asyncio.run(reviewer.review())


if __name__ == '__main__':
    main()
